name: GitHub Actions
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Update
        run: |
          sudo apt-get update
          sudo apt-get -y install locale
          localedef -f UTF-8 -i ja_JP ja_JP.UTF-8
      - name: Install Vim
        run: |
          sudo apt-get install -y vim less
      - name: Setup Python
        run: |
          pip install --upgrade pip
          pip install --upgrade setuptools
          python -m pip install jupyterlab